### ISSUE TITLE
Is it possible to wrap a formGroup ?

### ISSUE THREAD

**Issue by fluminis** [simontonsoftware/s-ng-utils#3]
Is it possible to wrap a form group?
`WrappedFormControlSuperclass` work very well for wrapping a single formControl but how can we wrap a formGroup?

I use `WrappedFormControlSuperclass` to wrap my application form controls. But now I want to group some of this control into reusable component. How it is possible?

Example my app-address-form template should look like this:
```
<app-form-input label="Street" controlName="street"></app-form-input>
<app-form-input label="Ville *" placeholder="Ville" controlName="city"></app-form-input>
<app-form-input label="Code postal" placeholder="Code postal" controlName="zipCode"></app-form-input>
```
And being able to use it:
`<app-address-form [formGroup]="myGroup"></app-address-group>`

Thanks in advance,
And thank you for this lib!

**Comment by ersimont** [comment]
Hmm interesting question. Have you tried passing the form group to your address component via an `@Input()` of a different name? E.g. something like:
```ts
@Component({
  selector: 'app-address-form',
  template: `
    <ng-container [formGroup]="formGroupPassthrough">
      <app-form-input label="Street" controlName="street"></app-form-input>
      <app-form-input label="Ville *" placeholder="Ville" controlName="city"></app-form-input>
      <app-form-input label="Code postal" placeholder="Code postal" controlName="zipCode"></app-form-input>
    </ng-container>
  `,
})
export class AddressFormComponent {
  @Input() formGroupPassthrough: FormGroup;
}
```
Then to use it:
```html
<app-address-form [formGroupPassthrough]="myGroup"></app-address-group>
```
(Sorry that code is untested - I wanted to get you a suggestion quickly before I head out for the day.)

**Comment by fluminis** [comment]
I tryed some solutions, the one is currently working seems to be :

`<app-form-group [formGroup]="myFormGroup.addressesArray.at(selectedIndex)" [addressGroup]="myFormGroup.addressesArray.at(selectedIndex)"></app-form-group>`

Without formGroup, the inner components are initialized correctly but are not updated when selectedIndex  changed.

Whith it, everything work. But it's a lot of repetition...

**Comment by ersimont** [comment]
Yes, that is a lot of repetition. :( I'm surprised the additional `[formGroup]` changes anything. I'm glad you found a working solution, though.
